spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskit?useSSL=false&serverTimezone=UTC
    username: root
    password: 0803
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  name: springbackend
logging:
  level:
    org.springframework: INFO
    org.gla.springbackend: DEBUG

